#
# Hand-maintained hardware configuration for the 2017 MacBook Air (A1466).
# This is a starter file; regenerate from the live machine after install only
# if hardware topology, exposed firmware interfaces, or required initrd module
# detection changes, then review the diff before merging.
# Last reviewed: 2026-05-18.
{ modulesPath, ... }:
{
  imports = [
    "${modulesPath}/installer/scan/not-detected.nix"
  ];

  boot = {
    # Apple NVMe (Samsung-built) lives on the standard nvme controller; xhci
    # covers USB 3 ports, ahci covers the legacy SATA controller exposed for
    # firmware updates. No TPM modules — pre-2018 MacBook Air has no T2.
    initrd.availableKernelModules = [
      "xhci_pci"
      "ahci"
      "nvme"
      "usb_storage"
      "sd_mod"
    ];
    kernelModules = [
      "kvm-intel"
    ];
    extraModulePackages = [ ];
  };

  # fileSystems and swapDevices are generated by disko (see disko.nix).
}
