#!/bin/bash
set -euo pipefail

THEME="${1:-}"
THEMES_DIR="$HOME/.config/themes"
# ACTIVE_FILE is injected by the theme module (themes.activeFile); the theme
# definitions live next to it.
REPO_THEMES_DIR="$(dirname "$ACTIVE_FILE")/themes"
LINKS_FILE="$THEMES_DIR/links.sh"
LOCK_FILE="${XDG_RUNTIME_DIR:-/tmp}/theme-switch.lock"
WAYBAR_PENDING_RELOAD="${XDG_STATE_HOME:-$HOME/.local/state}/waybar/needs-reload"

exec 9>"$LOCK_FILE"
flock 9

list_themes() {
  find "$REPO_THEMES_DIR" -maxdepth 1 -type f -name '*.nix' -printf '%f\n' |
    sed 's/\.nix$//' |
    sort
}

# A theme is defined in the repo (so it can be selected for the next rebuild)…
theme_in_repo() {
  [[ -f "$REPO_THEMES_DIR/$1.nix" ]]
}

# …and is switchable at runtime only once Home Manager has generated its assets.
theme_built() {
  [[ -d "$THEMES_DIR/$1" && -f "$THEMES_DIR/$1/vars" ]]
}

waybar_pids() {
  ps -eo pid=,comm=,args= |
    awk '$2 == ".waybar-wrapped" && $3 == "waybar" { print $1 }
         $2 == "waybar" { print $1 }' |
    sort -n -u
}

swaybg_pids() {
  ps -eo pid=,comm=,args= |
    awk '($2 == "swaybg" || $2 == ".swaybg-wrapped") && $0 ~ /swaybg -m fill -i .*current[.]png/ { print $1 }' |
    sort -n -u
}

waybar_visible() {
  # Visible waybar sits at layer level 2 ("top"); SIGUSR1 drops it to level 1
  # ("bottom") where it stays running but unseen. Checking the layer level is
  # the authoritative signal — the launcher uses the same check.
  hyprctl layers 2>/dev/null | awk '
    /^[[:space:]]*Layer level 2/  { in_top = 1; next }
    /^[[:space:]]*Layer level/    { in_top = 0; next }
    in_top && /namespace: waybar/ { found = 1; exit }
    END { exit !found }
  '
}

# Get current theme from active.nix
if [[ -f $ACTIVE_FILE ]]; then
  CURRENT_THEME=$(grep -oP 'themes/\K[^.]+' "$ACTIVE_FILE" 2>/dev/null || echo "unknown")
else
  CURRENT_THEME="unknown"
fi

# List available themes if no argument
if [[ -z $THEME ]]; then
  echo "Available themes:"
  list_themes
  echo ""
  echo "Current theme: $CURRENT_THEME"
  echo ""
  echo "Usage: theme-switch <theme-name>"
  exit 0
fi

# Validate theme exists
if ! theme_in_repo "$THEME"; then
  echo "Error: Theme not found: $THEME"
  echo "Available themes:"
  list_themes
  exit 1
fi

# Assets are generated by Home Manager (home/theme/module.nix). A theme added to
# the repo but not yet built can't be switched to at runtime.
if ! theme_built "$THEME"; then
  echo "Error: Theme '$THEME' is defined but its assets aren't built yet."
  echo "Run 'rebuild' to generate them, then switch."
  exit 1
fi

# Check if already active
if [[ $CURRENT_THEME == "$THEME" ]]; then
  if [[ -z $(swaybg_pids) ]]; then
    swaybg -m fill -i "$HOME/.local/share/wallpapers/current.png" 9>&- &
    echo "Theme '$THEME' is already active; restarted wallpaper"
  else
    echo "Theme '$THEME' is already active"
  fi
  exit 0
fi

# Update active.nix
if [[ ! -f $ACTIVE_FILE ]]; then
  echo "Error: $ACTIVE_FILE not found"
  exit 1
fi

echo "import ./themes/$THEME.nix" >"$ACTIVE_FILE"
echo "Updated active.nix to $THEME"

# Reuse the generated symlink map from Home Manager to avoid duplicating paths.
if [[ ! -f $LINKS_FILE ]]; then
  echo "Error: $LINKS_FILE not found"
  exit 1
fi

# shellcheck source=/dev/null
source "$LINKS_FILE"
link_theme_assets "$THEMES_DIR/$THEME"

# Live-reload colors come straight from the Nix-generated vars file, so this
# script never re-parses theme .nix definitions (Nix is the single source).
# Declared here so their origin is unambiguous; the source below fills them in.
bg='' brown='' amber=''
# shellcheck source=/dev/null
source "$THEMES_DIR/$THEME/vars"

if [[ -f /tmp/control-center.json ]]; then
  control_center_pid=$(
    sed -n 's/.*"pid"[[:space:]]*:[[:space:]]*\([0-9]\+\).*/\1/p' \
      /tmp/control-center.json | head -1
  )
  if [[ -n ${control_center_pid:-} ]] && kill -0 "$control_center_pid" 2>/dev/null; then
    kill -USR2 "$control_center_pid" 2>/dev/null || true
  fi
fi

# Reload apps
hyprctl keyword general:col.active_border "rgb($amber)" >/dev/null 2>&1 || true
hyprctl keyword general:col.inactive_border "rgb($brown)" >/dev/null 2>&1 || true
hyprctl keyword decoration:shadow:color "rgba(${bg}cc)" >/dev/null 2>&1 || true

if waybar_visible; then
  while IFS= read -r pid; do
    [[ -n $pid ]] || continue
    kill -USR2 "$pid" 2>/dev/null || true
  done < <(waybar_pids)
  rm -f "$WAYBAR_PENDING_RELOAD"
else
  # Defer the reload until the bar is un-hidden so SIGUSR2 doesn't bring it
  # back into view. waybar-toggle consumes this flag on its next show.
  mkdir -p "$(dirname "$WAYBAR_PENDING_RELOAD")"
  : >"$WAYBAR_PENDING_RELOAD"
fi

# Warm the kernel page cache so swaybg's decode is CPU-bound, not disk-bound.
# Cold reads of large wallpapers (mono-mesh.jpg 5.2M, desert-dusk.png 8M) push
# the buffer commit past the handover window and the compositor briefly falls
# back to its default wallpaper.
cat "$HOME/.local/share/wallpapers/current.png" >/dev/null 2>&1 || true

old_swaybg_pids=()
while IFS= read -r pid; do
  [[ -n $pid ]] && old_swaybg_pids+=("$pid")
done < <(swaybg_pids)
swaybg -m fill -i "$HOME/.local/share/wallpapers/current.png" 9>&- &
sleep 0.5
if ((${#old_swaybg_pids[@]} > 0)); then
  kill "${old_swaybg_pids[@]}" 2>/dev/null || true
  sleep 0.2
  for pid in "${old_swaybg_pids[@]}"; do
    kill -0 "$pid" 2>/dev/null && kill -KILL "$pid" 2>/dev/null || true
  done
fi

ps -eo pid=,comm= |
  awk '$2 == ".kitty-wrapped" || $2 == "kitty" { print $1 }' |
  xargs -r kill -USR1 2>/dev/null || true

if ! systemctl --user restart mako.service 2>/dev/null; then
  pkill -x mako 2>/dev/null || true
  sleep 0.2
  systemctl --user restart mako.service 2>/dev/null || true
fi
systemctl --user reset-failed mako.service 2>/dev/null || true

notify-send "Theme changed" "Switched to: $THEME" || true
echo "✓ Theme switched to $THEME"
