#
# Hand-maintained hardware configuration.
# Regeneration policy: do not blindly overwrite this file; regenerate from the
# target machine only after hardware topology, firmware-facing device exposure,
# or required kernel module detection changes, then review the diff before
# merging.
# Last reviewed: 2026-05-16.
{ modulesPath, ... }:
{
  imports = [
    "${modulesPath}/installer/scan/not-detected.nix"
  ];

  boot = {
    initrd.availableKernelModules = [
      "xhci_pci"
      "ahci"
      "nvme"
      "usb_storage"
      "sd_mod"
      "tpm_tis"
      "tpm_crb"
    ];
    kernelModules = [
      "kvm-intel"
      "tpm_tis"
      "tpm_crb"
    ];
    extraModulePackages = [ ];
  };

  # fileSystems and swapDevices are generated by disko (see disko.nix)
}
